---
title: "Explanation: Limitations and known issues"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Explanation: Limitations and known issues}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# GitHub Actions CI
Rhino comes with a CI workflow (Continuous Integration)
for [GitHub Actions](https://docs.github.com/en/actions)
which automatically runs linters and tests whenever you push to the repository.
Your application must live in the root of your git repository for it to work.
In particular, CI won't work if you have multiple Rhino applications
in subdirectories of your repository.

Rhino might support this use case in the future.
Meanwhile it is possible to work around this issue:

1. Place all workflows in the `.github/workflows` directory.
2. Adjust each workflow by setting
a [default working directory](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun)
accordingly.

# Box package
Rhino uses the [box](https://klmr.me/box/) R package to provide modularization for your code
in a similar fashion to languages like Python and Java.
The package is in active development so bugs are being discovered and fixed.

### Lazy-loaded data
Box 1.1.0 doesn't support lazy-loaded [data](https://r-pkgs.org/data.html#data-data),
so e.g. `box::use(datasets[mtcars])` won't work.
This feature should be available in the next release
(see this [issue](https://github.com/klmr/box/issues/219)).
For now please use `datasets::mtcars` in your code.

### Trailing commas
Box 1.1.0 allows trailing commas in `box::use()` statements and code,
but they can cause problems in some circumstances:

1. Reexports ([issue](https://github.com/klmr/box/issues/263)).
2. Functions accessed via `$` ([issue](https://github.com/klmr/box/issues/266)).

Both issues should be fixed in the nearest release.
