---
title: "How-to: Use global variables"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How-to: Use global variables}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Rhino uses [`box`](https://appsilon.github.io/rhino/articles/explanation/box-modules.html) to ensure reusable and modular code, both from using packages and using the scripts within the app itself. Rhino favors the explicit over the implicit, and a local scope over  a global scope.

However, there are some instances when developers may need to use global variables in their app. In such cases, Rhino suggests the following ways to handle global variables.

> Rhino **DOES NOT** encourage the use of global variables. Rhino encourages modular code with definitions limited to their own scope as much as possible. It is only at the greatest of needs that global variables should be used.

# Global Variables 

## Creating Constants

Storing constants is the most common reason and usage for a global variable.

The suggested way to create global constants in Rhino is to define and export the constant inside its own `R` script in `app/logic`.

```r
# app/logic/constant.R
#' @export
answer <- 42
```

The global constant can be imported and used in other modules.

```r
# app/logic/another_module.R
box::use(app/logic/constant[answer])
```

## Updating a Global Variable

In `R`, [global variables live inside `.GlobalEnv`](http://adv-r.had.co.nz/Environments.html). Global variables can be updated within a function using `<<-`.

```{r base-r-global-variable, eval=TRUE, collapse=TRUE, comment=">"}
answer <- 42

change_answer <- function(new_answer, is_global = FALSE) {
  if (is_global) {
    answer <<- new_answer
  } else {
    answer <- new_answer
  }

  answer
}

change_answer(25)

answer

change_answer(25, is_global = TRUE)

answer
```

When code is loaded with `box::use()`, global variables live inside the [module's own immutable environment](https://klmr.me/box/articles/mod-env-hierarchy.html#environments-1). Updating global variables with `<<-` will not work.

```r
# app/logic/answer.R
answer <- 42
```

```r
# app/logic/update_answer.R
box::use(app/logic/answer[answer])

#' @export
update_answer <- function() {
  answer <<- 25
}
```

```r
# app/logic/get_answer.R
box::use(
  app/logic/answer,
  app/logic/update_answer[update_answer]
)

update_answer()

answer # This still returns 42
```

### Variables in a New Environment

To overcome `box`'s feature of limiting scope, Rhino suggests creating a new environment and use that environment to contain the global variables.

```r
# app/logic/global.R
#' @export
global <- new.env()
```

```r
# app/logic/answer.R
box::use()

global$answer <- 42
```

```r
# app/logic/update_answer.R
box::use(
  app/logic/global[global],
  app/logic/answer
)

#' @export
update_answer <- function() {
  .GlobalEnv$answer <- 25
}
```

```r
# app/logic/get_answer.R
box::use(
  app/logic/global[global],
  app/logic/answer,
  app/logic/update_answer[update_answer]
)

update_answer()

answer # This returns 25
```

### Variables in `.GlobalEnv`

Alternatively, variables can still be stored in and imported from `.GlobalEnv`. The variable must also be defined and updated using `<-`.

```r
# app/logic/answer.R
.GlobalEnv$answer <- 42
```

```r
# app/logic/update_answer.R
box::use(app/logic/answer)

#' @export
update_answer <- function() {
  .GlobalEnv$answer <- 25
}
```

```r
# app/logic/get_answer.R
box::use(
  app/logic/answer,
  app/logic/update_answer[update_answer]
)

update_answer()

answer # This returns 25
```

# Session Variables

Rhino suggests using arguments in module servers for explicit handling of session variables or user inputs.

```r

module_ui <- function(id) {
  ns <- NS(id)
  textOutput(ns("answer"))
}

module_server <- function(id, answer) {
  moduleServer(id, function(input, output, session) {
    output$answer <- renderText(answer())
  })
}

shinyApp(
  ui = bootstrapPage(
    textInput("answer", "Answer"),
    module_ui("module")
  ),
  server = function(input, output, session) {
    answer <- reactiveVal()
    observeEvent(input$answer, answer(input$answer))

    module_server("module", answer())
  }
)
```

However, `shiny` has support for [`session$userData`](https://shiny.rstudio.com/reference/shiny/latest/session.html), an environment that can store session-specific data. 

```r

module_ui <- function(id) {
  ns <- NS(id)
  textOutput(ns("answer"))
}

module_server <- function(id) {
  moduleServer(id, function(input, output, session) {
    output$answer <- renderText(session$userData$answer())
  })
}

shinyApp(
  ui = bootstrapPage(
    textInput("answer", "Answer"),
    module_ui("module")
  ),
  server = function(input, output, session) {
    session$userData$answer <- reactiveVal()
    observeEvent(input$answer, session$userData$answer(input$answer))

    module_server("module")
  }
)
```

All modules have access to the variables inside `session$userData`.
