variables:
  # For caching renv library
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/cache
  RENV_PATHS_LIBRARY: ${CI_PROJECT_DIR}/renv/library
  # Cache .rhino
  DOT_RHINO_PATH: ${CI_PROJECT_DIR}/.rhino
  # Necessary for cypress to run.
  # https://docs.cypress.io/guides/references/error-messages#A-Cached-Cypress-Binary-Could-not-be-found
  # https://docs.cypress.io/guides/continuous-integration/introduction#Caching
  CYPRESS_CACHE_FOLDER: ${CI_PROJECT_DIR}/.cache/Cypress


default:
  # Use deployed image with .gitlab-ci.Dockerfile
  image: your/image:latest
  cache:
    # This key needs to be constant so all jobs in all branches will share the same cache
    key: rhino-ci
    paths:
      - ${RENV_PATHS_CACHE}
      - ${RENV_PATHS_LIBRARY}
      - ${DOT_RHINO_PATH}
      - ${CYPRESS_CACHE_FOLDER}

Runs linters and tests:
  before_script:
    # Restores renv when cache is not available.
    - R -e "options(renv.config.cache.symlinks = FALSE); renv::restore(clean = TRUE);"
  script:
    - R -e "rhino::lint_r()"
    - R -e "rhino::lint_sass()"
    - R -e "rhino::lint_js()"
    - R -e "rhino::build_sass()"
    - R -e "rhino::build_js()"
    - R -e "rhino::test_r()"
    - R -e "rhino::test_e2e()"