blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://appsilon.github.io/rhino/
    about: Learn about Rhino from our extensive documentation
  - name: Discussions
    url: https://github.com/Appsilon/rhino/discussions
    about: Use the board for questions and general discussion
