project:
  type: website

website:
  title: "Rhino"
  navbar:
    left:
      - text: Tutorial
        href: tutorial/tutorial.qmd
      - text: Explanation
        href: explanation/rhino-project-structure.qmd
      - text: How-to Guides
        href: index.qmd
      - text: Reference
        href: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/Appsilon/rhino

format:
  html:
    theme: cosmo
