project:
  type: website

website:
  title: "quarto"
  navbar:
    background: primary
    left:
      - text: Home
        href: index.qmd
      - about.qmd
      - text: Reference
        href: reference/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
