project:
  type: website

website:
  title: "Rhino"
  navbar:
    left:
      - text: Tutorial
        href: index.qmd
      - text: Explanation
        href: index.qmd
      - text: How-to Guides
        href: index.qmd
      - text: Reference
        href: reference/index.qmd

format:
  html:
    theme: cosmo
