on: push

name: E2E Test

defaults:
 run:
  working-directory: ./tests/e2e/

jobs:
  main:
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    runs-on: ${{ matrix.config.os }}

    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: macOS-latest,   r: 'release'}
        - {os: windows-latest, r: 'release'}
        - {os: ubuntu-22.04, r: 'devel'}
        - {os: ubuntu-22.04, r: 'release'}
        - {os: ubuntu-22.04, r: 'oldrel'}

    steps:
      - name: Checkout E2E Directory
        uses: Bhacaz/checkout-files@v2
        with:
          files: tests/e2e

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install Rhino
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: Appsilon/rhino@${{ github.sha }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: init() should create a Rhino directory
        if: always()
        shell: Rscript {0}
        run: rhino::init('RhinoApp')

      - name: Test R
        if: always()
        run: |
          cd RhinoApp
          Rscript -e 'rhino::test_r()'
