name: pkgdown
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  pkgdown:
    name: Build and publish website
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true # Dramatically speeds up installation of dependencies.

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.

      - name: Build site
        shell: Rscript {0}
        run: |
          source("pkgdown/build.R")
          build_versioned(
            repo = ".",
            versions = yaml::read_yaml("pkgdown/versions.yaml"),
            url = "https://appsilon.github.io/rhino",
            destination = "docs"
          )

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: bot/github-pages
