name: pkgdown
on:
  # Run when a release is published, or a pre-release is changed to a release. Reference:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  # https://docs.github.com/en/webhooks/webhook-events-and-payloads#release
  release:
    types: [released]
  # It is also possible to manually trigger this workflow for a selected tag/branch
  # from the "Actions" tab on GitHub.
  workflow_dispatch:
permissions:
  contents: write
jobs:
  pkgdown:
    name: Build and publish website
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true # Dramatically speeds up installation of dependencies.

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, any::remotes, local::.

      - name: Build site
        shell: Rscript {0}
        run: |
          source("pkgdown/build.R")
          build_versioned(
            repo = ".",
            versions = yaml::read_yaml("pkgdown/versions.yaml"),
            url = "https://appsilon.github.io/rhino",
            destination = "docs"
          )

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: bot/github-pages
